FROM debian

MAINTAINER ieropaie <ieropaie@student.42.us.org>

RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential git

# How to build it?
# docker build -t a00 .

# How to run it?
# docker run --rm -ti a00

# C enviroment 
