FROM ubuntu

MAINTAINER ieropaie <ieropaie@student.42.us.org>

RUN apt-get update && apt-get upgrade -y && apt-get install -y default-jdk default-jre git vim emacs

# How to build it?
# docker build -t a01 .

# How to run it?
# docker run --rm -ti a01

#Java enviroment
